export default [
  "weather forecaster",
  "how to tie a tie",
  "funny cat videos",
  "local movie times",
  "translate hello",
  "stock market simulation",
  "coffee shops",
  "best books 2024",
  "easy dinner recipes",
  "travel tips",
  "what is AI",
  "top songs",
  "fitness workouts",
  "DIY home decor",
  "coding tutorials",
  "cheap flights",
  "free games",
  "learn javascript",
  "celebrity news",
  "math help",
  "weather app",
  "best restaurants",
  "top movies",
  "job openings",
  "how to cook rice",
  "instagram login",
  "youtube trending",
  "daily horoscope",
  "python examples",
  "guitar chords",
  "email sign up",
  "quotes of the day",
  "online courses",
  "sports scores",
  "pet care tips",
  "download pdf",
  "how to lose weight",
  "bitcoin price",
  "grammar checker",
  "vacation ideas",
  "resume examples",
  "calendar 2025",
  "css tricks",
  "html basics",
  "shopping deals",
  "movie trailers",
  "best laptops",
  "coding challenges",
  "gaming news",
  "art tutorials",
  "healthy snacks",
  "how to meditate",
  "finance tips",
  "best shoes",
  "language learning",
  "daily affirmations",
  "mental health tips",
  "gardening ideas",
  "free eBooks",
  "live TV",
  "science facts",
  "music theory",
  "baking recipes",
  "online tools",
  "photo editor",
  "how to save money",
  "budget planner",
  "fun quizzes",
  "keto recipes",
  "car reviews",
  "baby names",
  "coding interview",
  "marketing ideas",
  "team productivity",
  "study techniques",
  "cryptocurrency",
  "AI tools",
  "project ideas",
  "how to draw",
  "language translator",
  "typing test",
  "cloud storage",
  "best podcasts",
  "quick workouts",
  "habit tracker",
  "email templates",
  "movie reviews",
  "nutrition facts",
  "writing prompts",
  "brain teasers",
  "travel checklist",
  "best cameras",
  "school supplies",
  "gift ideas",
  "public speaking tips",
  "hiking trails",
  "self-care tips",
  "resume builder",
  "pasta recipes",
  "build a website",
  "calorie calculator",
  "file converter",
  "start a blog",
  "read manga online",
  "free stock photos",
  "learn spanish",
  "photo collage maker",
  "edit pdf",
  "weather radar",
  "mindfulness exercises",
  "best coding languages",
  "online banking",
  "job interview tips",
  "online resume",
  "career advice",
  "run faster tips",
  "learn piano",
  "kids games",
  "word counter",
  "chess tactics",
  "birthday wishes",
  "how to invest",
  "file compressor",
  "color picker",
  "laptop reviews",
  "time zones",
  "how to focus",
  "motivational quotes",
  "home workout plan",
  "learn to read",
  "shopping list",
  "free music",
  "print calendar",
  "language quiz",
  "how to start coding",
  "podcast ideas",
  "skincare tips",
  "how to stay awake",
  "weight gain foods",
  "how to write a story",
  "learn algebra",
  "save battery life",
  "recycling guide",
  "laundry symbols",
  "pet training",
  "top apps",
  "camera settings",
  "photo backup",
  "daily planner",
  "recipe generator",
  "simple workouts",
  "beginner yoga",
  "productivity apps",
  "meditation timer",
  "online whiteboard",
  "interior design tips",
  "flashcard maker",
  "goal setting",
  "freelance jobs",
  "UX design tips",
  "app ideas",
  "VR games",
  "budget travel",
  "online stopwatch",
  "reading list",
  "morning routine",
  "free audiobooks",
  "color theory",
  "financial goals",
  "how to speak clearly",
  "solar system facts",
  "career change tips",
  "daily journaling",
  "free resume builder",
  "best exercises",
  "write a poem",
  "fun facts",
  "rain sounds",
  "concentration music",
  "recipe app",
  "design portfolio",
  "how to code a game",
  "funny memes",
  "upload files",
  "cloud backup",
  "digital marketing tips",
  "first aid basics",
  "how to sleep better",
  "cooking conversions",
  "minimalist living",
  "life hacks",
  "color combinations",
  "image optimizer",
  "keyboard shortcuts",
  "meal planner",
  "time tracker",
  "digital drawing",
  "free fonts",
  "daily checklist",
  "best novels",
  "learn geography",
  "how to write faster",
  "positive habits",
  "morning motivation",
  "book summaries",
  "free design tools",
  "how to reduce stress",
  "how to take notes"
];